# Generated by Django 3.2.23 on 2026-05-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0011_secretleak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='techs',
            field=models.ManyToManyField(blank=True, related_name='techs', to='startScan.Technology'),
        ),
    ]
