# Generated by Django 3.2.23 on 2026-05-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0003_alter_domain_monitor_frequency'),
        ('startScan', '0012_alter_endpoint_techs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='criticality_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='criticality_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='correlation_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_suppressed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImpactAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('simulated_path', models.JSONField(blank=True, null=True)),
                ('potential_attack_chain', models.JSONField(blank=True, null=True)),
                ('potential_impact', models.TextField(blank=True, null=True)),
                ('remediation_priority', models.IntegerField(default=1)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.vulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='FalsePositiveRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_id', models.CharField(max_length=200)),
                ('regex_pattern', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
    ]
