# Generated by Django 3.2.23 on 2026-05-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0003_alter_domain_monitor_frequency'),
        ('startScan', '0013_auto_20260504_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_used', models.CharField(default='k6', max_length=50)),
                ('concurrency_used', models.IntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('avg_latency_ms', models.FloatField(default=0.0)),
                ('p95_latency_ms', models.FloatField(default=0.0)),
                ('p99_latency_ms', models.FloatField(default=0.0)),
                ('max_requests_per_second', models.FloatField(default=0.0)),
                ('is_kill_switch_triggered', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_results', to='startScan.scanhistory')),
                ('target_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stress_results', to='targetApp.domain')),
            ],
            options={
                'verbose_name': 'Stress Test Result',
                'verbose_name_plural': 'Stress Test Results',
            },
        ),
    ]
