# Generated by Django 3.2.23 on 2026-05-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0014_stresstestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveid',
            name='is_cisa_kev',
            field=models.BooleanField(default=False),
        ),
    ]
