# Generated by Django 3.2.23 on 2026-05-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0015_cveid_is_cisa_kev'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='validation_confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('payload', models.TextField(blank=True, null=True)),
                ('request_evidence', models.TextField(blank=True, null=True)),
                ('response_evidence', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='startScan.vulnerability')),
            ],
        ),
    ]
