# Generated by Django 3.2.23 on 2026-05-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0016_auto_20260507_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('screenshot_path', models.CharField(max_length=1000)),
                ('html_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('favicon_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('technologies', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='startScan.subdomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
