# Generated by Django 3.2.23 on 2026-05-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0017_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCandidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=2000)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('smb', 'SMB'), ('rdp', 'RDP'), ('ssh', 'SSH'), ('ftp', 'FTP'), ('telnet', 'Telnet')], max_length=20)),
                ('port', models.IntegerField()),
                ('source_tool', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.endpoint')),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('subdomain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startScan.subdomain')),
            ],
            options={
                'verbose_name_plural': 'Authentication Candidates',
                'unique_together': {('scan_history', 'target', 'protocol', 'port')},
            },
        ),
    ]
