# Generated by Django 3.2.23 on 2026-05-08 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0018_authcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('report_template', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3)], default=-1)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='startScan.scanhistory')),
            ],
            options={
                'verbose_name_plural': 'Scan Reports',
            },
        ),
    ]
