# Generated by Django 3.2.23 on 2026-05-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0019_scanreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employee',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
