# Generated by Django 3.2.23 on 2026-05-21 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0021_alter_vulnerability_validation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTelemetryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('k6', 'k6'), ('wrk', 'wrk'), ('hping3', 'hping3'), ('locust', 'locust'), ('stressor', 'stressor')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('throughput', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('request_count', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(blank=True, null=True)),
                ('tool_specific_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stress Telemetry Point',
                'verbose_name_plural': 'Stress Telemetry Points',
            },
        ),
        migrations.CreateModel(
            name='StressToolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_configs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stress Tool Configuration',
                'verbose_name_plural': 'Stress Tool Configurations',
            },
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='anomalies_detected',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='endpoints_tested',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='error_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='findings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='max_concurrent_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='p50_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='p75_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='p90_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='p999_latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='peak_throughput_rps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='percentile_latencies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='recommendations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='response_code_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stresstestresult',
            name='test_status',
            field=models.CharField(choices=[('success', 'Success'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('running', 'Running')], default='success', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stresstestresult',
            index=models.Index(fields=['scan_history', '-start_time'], name='startScan_s_scan_hi_093f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='stresstestresult',
            index=models.Index(fields=['test_status'], name='startScan_s_test_st_14520b_idx'),
        ),
        migrations.AddField(
            model_name='stresstoolconfiguration',
            name='stress_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_config', to='startScan.stresstestresult'),
        ),
        migrations.AddField(
            model_name='stresstelemetrypoint',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.endpoint'),
        ),
        migrations.AddField(
            model_name='stresstelemetrypoint',
            name='stress_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='startScan.stresstestresult'),
        ),
        migrations.AddIndex(
            model_name='stresstelemetrypoint',
            index=models.Index(fields=['stress_result', 'timestamp'], name='startScan_s_stress__f658b7_idx'),
        ),
        migrations.AddIndex(
            model_name='stresstelemetrypoint',
            index=models.Index(fields=['tool', 'timestamp'], name='startScan_s_tool_1b4cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='stresstelemetrypoint',
            index=models.Index(fields=['endpoint', 'timestamp'], name='startScan_s_endpoin_675813_idx'),
        ),
    ]
