# Generated by Django 3.2.23 on 2026-05-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0021_alter_vulnerability_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='is_redirect',
            field=models.BooleanField(default=False),
        ),
    ]
