# Generated by Django 3.2.23 on 2026-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0022_endpoint_is_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanhistory',
            name='scan_status',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1),
        ),
        migrations.AlterField(
            model_name='scanreport',
            name='status',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=-1),
        ),
    ]
