# Generated by Django 3.2.23 on 2026-05-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0004_auto_20260509_1015'),
        ('startScan', '0024_impact_assessment_unique_vuln_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintStaging',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('osint_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('confidence', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('discovered_date', models.DateTimeField(auto_now_add=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
                ('target_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
            options={
                'verbose_name_plural': 'OSINT Staging',
            },
        ),
    ]
