# Generated by Django 3.2.23 on 2026-05-21 10:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0005_auto_20260518_1246'),
        ('startScan', '0025_osintstaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalWorkflowExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(max_length=255, unique=True)),
                ('run_id', models.CharField(max_length=255)),
                ('workflow_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='RUNNING', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_executions', to='startScan.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSuppressionState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=500)),
                ('suppressed_until', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('target_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targetApp.domain')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSignal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signal_name', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='startScan.temporalworkflowexecution')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowLineage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=50)),
                ('depth', models.IntegerField(default=0)),
                ('child_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_lineages', to='startScan.temporalworkflowexecution')),
                ('parent_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_lineages', to='startScan.temporalworkflowexecution')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='startScan.temporalworkflowexecution')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCheckpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkpoint_name', models.CharField(max_length=100)),
                ('state_payload', models.JSONField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.temporalworkflowexecution')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalActivityExecution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_id', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='RUNNING', max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_telemetry', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='startScan.temporalworkflowexecution')),
            ],
        ),
        migrations.CreateModel(
            name='RecursiveExpansionState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=1000)),
                ('depth', models.IntegerField(default=0)),
                ('budget_allocated', models.IntegerField(default=100)),
                ('budget_consumed', models.IntegerField(default=0)),
                ('ancestry_path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None)),
                ('expansion_score', models.FloatField(default=1.0)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='OASTCorrelationState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('workflow_id', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_correlated', models.BooleanField(default=False)),
                ('interaction_payload', models.JSONField(blank=True, null=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startScan.scanhistory')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionTelemetry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('active_threads', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='startScan.temporalworkflowexecution')),
            ],
        ),
    ]
