# Generated by Django 3.2.23 on 2026-05-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0022_auto_20260521_1728'),
        ('startScan', '0026_executiontelemetry_oastcorrelationstate_recursiveexpansionstate_temporalactivityexecution_temporalwo'),
    ]

    operations = [
    ]
