# Generated by Django 3.2.23 on 2026-05-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0027_merge_20260521_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresstestresult',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
