# Generated by Django 3.2.23 on 2026-05-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0005_auto_20260518_1246'),
        ('startScan', '0028_alter_stresstestresult_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('workflow_type', models.CharField(max_length=100)),
                ('workflow_args', models.JSONField(default=dict)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100)),
                ('interval_seconds', models.IntegerField(blank=True, null=True)),
                ('clocked_time', models.DateTimeField(blank=True, null=True)),
                ('one_off', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_run_count', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_schedules', to='targetApp.domain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
