# Generated by Django 3.2.23 on 2026-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0030_rename_celery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='recovery_count',
            field=models.IntegerField(default=0),
        ),
    ]
