# Generated by Django 3.2.23 on 2026-05-30 13:21 (manually patched for unique UUID per-row)

import uuid
from django.db import migrations, models
import django.db.models.deletion


def _assign_task_uids(apps, schema_editor):
    ScanActivity = apps.get_model('startScan', 'ScanActivity')
    for row in ScanActivity.objects.filter(task_uid__isnull=True):
        row.task_uid = uuid.uuid4()
        row.save(update_fields=['task_uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0031_scanhistory_recovery_count'),
    ]

    operations = [
        # 1. Add other nullable fields first
        migrations.AddField(
            model_name='scanactivity',
            name='subscan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='startScan.subscan'),
        ),
        migrations.AddField(
            model_name='scanactivity',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanactivity',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanactivity',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # 2. Add task_uid as nullable (no unique yet) so we can populate existing rows
        migrations.AddField(
            model_name='scanactivity',
            name='task_uid',
            field=models.UUIDField(db_index=True, null=True, blank=True),
        ),
        # 3. Assign a unique UUID4 to every existing row
        migrations.RunPython(_assign_task_uids, migrations.RunPython.noop),
        # 4. Now make it non-nullable + unique
        migrations.AlterField(
            model_name='scanactivity',
            name='task_uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
