# Generated by Django 3.2.23 on 2026-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0033_vulnerability_group_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authcandidate',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='authcandidate',
            constraint=models.UniqueConstraint(fields=('scan_history', 'target', 'protocol', 'port'), name='unique_authcandidate_scan_target_proto_port'),
        ),
    ]
