# Generated by Django 5.2.3 on 2026-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0034_convert_authcandidate_unique_to_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveid',
            name='attack_complexity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='attack_vector',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='availability_impact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='confidentiality_impact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='cvss_v31_base_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='epss_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='epss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='integrity_impact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='privileges_required',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='related_cves',
            field=models.ManyToManyField(blank=True, related_name='related_from', to='startScan.cveid'),
        ),
        migrations.AddField(
            model_name='cveid',
            name='user_interaction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='vulnerability_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
