# Generated by Django 3.2.23 on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0034_convert_authcandidate_unique_to_constraint'),
    ]

    operations = [
        # Make name field unique and indexed
        migrations.AlterField(
            model_name='cveid',
            name='name',
            field=models.CharField(max_length=100, unique=True, db_index=True),
        ),
        
        # Add CVSS v3.1 fields
        migrations.AddField(
            model_name='cveid',
            name='cvss_v31_base_score',
            field=models.FloatField(null=True, blank=True, help_text='CVSS v3.1 Base Score (0-10)'),
        ),
        migrations.AddField(
            model_name='cveid',
            name='attack_vector',
            field=models.CharField(
                max_length=20, 
                null=True, 
                blank=True, 
                choices=[
                    ('NETWORK', 'Network'),
                    ('ADJACENT', 'Adjacent Network'),
                    ('LOCAL', 'Local'),
                    ('PHYSICAL', 'Physical'),
                ],
                help_text='CVSS Attack Vector'
            ),
        ),
        migrations.AddField(
            model_name='cveid',
            name='attack_complexity',
            field=models.CharField(
                max_length=20, 
                null=True, 
                blank=True, 
                choices=[
                    ('LOW', 'Low'),
                    ('HIGH', 'High'),
                ],
                help_text='CVSS Attack Complexity'
            ),
        ),
        migrations.AddField(
            model_name='cveid',
            name='privileges_required',
            field=models.CharField(
                max_length=20, 
                null=True, 
                blank=True, 
                choices=[
                    ('NONE', 'None'),
                    ('LOW', 'Low'),
                    ('HIGH', 'High'),
                ],
                help_text='CVSS Privileges Required'
            ),
        ),
        migrations.AddField(
            model_name='cveid',
            name='user_interaction',
            field=models.CharField(
                max_length=20, 
                null=True, 
                blank=True, 
                choices=[
                    ('NONE', 'None'),
                    ('REQUIRED', 'Required'),
                ],
                help_text='CVSS User Interaction'
            ),
        ),
        
        # Add impact fields
        migrations.AddField(
            model_name='cveid',
            name='confidentiality_impact',
            field=models.CharField(
                max_length=20, 
                null=True, 
                blank=True, 
                choices=[
                    ('NONE', 'None'),
                    ('LOW', 'Low'),
                    ('HIGH', 'High'),
                ],
                help_text='CVSS Confidentiality Impact'
            ),
        ),
        migrations.AddField(
            model_name='cveid',
            name='integrity_impact',
            field=models.CharField(
                max_length=20, 
                null=True, 
                blank=True, 
                choices=[
                    ('NONE', 'None'),
                    ('LOW', 'Low'),
                    ('HIGH', 'High'),
                ],
                help_text='CVSS Integrity Impact'
            ),
        ),
        migrations.AddField(
            model_name='cveid',
            name='availability_impact',
            field=models.CharField(
                max_length=20, 
                null=True, 
                blank=True, 
                choices=[
                    ('NONE', 'None'),
                    ('LOW', 'Low'),
                    ('HIGH', 'High'),
                ],
                help_text='CVSS Availability Impact'
            ),
        ),
        
        # Add EPSS fields
        migrations.AddField(
            model_name='cveid',
            name='epss_score',
            field=models.FloatField(
                null=True, 
                blank=True, 
                help_text='EPSS Score (0-1, higher = more likely to be exploited)'
            ),
        ),
        migrations.AddField(
            model_name='cveid',
            name='epss_percentile',
            field=models.FloatField(
                null=True, 
                blank=True, 
                help_text='EPSS Percentile (0-100, percentage of CVEs with lower EPSS)'
            ),
        ),
        
        # Add temporal fields
        migrations.AddField(
            model_name='cveid',
            name='published_date',
            field=models.DateTimeField(
                null=True, 
                blank=True, 
                db_index=True,
                help_text='Publication date from NVD'
            ),
        ),
        migrations.AddField(
            model_name='cveid',
            name='last_modified_date',
            field=models.DateTimeField(
                null=True, 
                blank=True, 
                help_text='Last modification date from NVD'
            ),
        ),
        
        # Add vulnerability type
        migrations.AddField(
            model_name='cveid',
            name='vulnerability_type',
            field=models.CharField(
                max_length=50, 
                null=True, 
                blank=True, 
                choices=[
                    ('SCA', 'Software Composition Analysis'),
                    ('SAST', 'Static Analysis'),
                    ('DAST', 'Dynamic Analysis'),
                    ('INFRASTRUCTURE', 'Infrastructure'),
                    ('CONFIG', 'Configuration'),
                    ('OTHER', 'Other'),
                ],
                help_text='Type of vulnerability'
            ),
        ),
        
        # Add related CVEs relationship
        migrations.AddField(
            model_name='cveid',
            name='related_cves',
            field=models.ManyToManyField(
                'self', 
                symmetrical=False, 
                blank=True,
                related_name='related_from',
                help_text='Other CVEs related to this one (e.g., in same chain)'
            ),
        ),
    ]
