# Generated by Django 5.2.3 on 2026-06-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0036_create_vulnerability_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vulnerabilityhistory',
            new_name='vh_groupkey_lastseen_idx',
            old_name='vh_groupkey_lastseen',
        ),
        migrations.RenameIndex(
            model_name='vulnerabilityhistory',
            new_name='vh_remediated_lastseen_idx',
            old_name='vh_remediated_lastseen',
        ),
        migrations.RenameIndex(
            model_name='vulnerabilityhistory',
            new_name='vh_scan_lastseen_idx',
            old_name='vh_scan_lastseen',
        ),
        migrations.AlterField(
            model_name='cveid',
            name='attack_complexity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='attack_vector',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='availability_impact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='confidentiality_impact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='cvss_v31_base_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='epss_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='epss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='integrity_impact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='privileges_required',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='related_cves',
            field=models.ManyToManyField(blank=True, related_name='related_from', to='startScan.cveid'),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='user_interaction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveid',
            name='vulnerability_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='cve',
            field=models.ForeignKey(blank=True, help_text='Associated CVE, if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='startScan.cveid'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, help_text='First discovery timestamp'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='group_key',
            field=models.CharField(db_index=True, help_text='SHA-256 hash for grouping identical vulnerabilities', max_length=500),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='is_remediated',
            field=models.BooleanField(default=False, help_text='Whether vulnerability has been fixed'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Most recent discovery timestamp'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='scan_history',
            field=models.ForeignKey(help_text='Scan that generated this history record', on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_history', to='startScan.scanhistory'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='total_occurrences',
            field=models.IntegerField(default=1, help_text='Total times this vulnerability appeared'),
        ),
        migrations.AlterField(
            model_name='vulnerabilityhistory',
            name='vulnerability',
            field=models.ForeignKey(help_text='Vulnerability that triggered this record', on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='startScan.vulnerability'),
        ),
    ]
