# Generated by Django 5.2.3 on 2026-06-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0013_hardwareprofile'),
        ('startScan', '0037_rename_vh_groupkey_lastseen_vh_groupkey_lastseen_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='hardware_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanEngine.hardwareprofile'),
        ),
    ]
