# Generated by Django 5.2.3 on 2026-06-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0038_scanhistory_hardware_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveid',
            name='is_poc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cveid',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
