# Generated by Django 5.2.3 on 2026-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0041_parameter_cpde_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cveid',
            name='ai_risk_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='hackerone_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cveid',
            name='mitigation_ideas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='patching_priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cveid',
            name='public_exploits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
