# Generated by Django 5.2.3 on 2026-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0042_cveid_ai_risk_assessment_cveid_hackerone_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='asn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='asn_cidr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='asn_org',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
