# Generated by Django 5.2.3 on 2026-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0043_ipaddress_asn_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpssFeedData',
            fields=[
                ('cve_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('epss_score', models.FloatField()),
                ('epss_percentile', models.FloatField()),
                ('date_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
