# Generated by Django 3.2.23 on 2026-05-07 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('anchor_step', models.CharField(help_text='Core engine task name this plugin attaches to', max_length=255)),
                ('runtime_position', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], default='AFTER', max_length=10)),
                ('order_weight', models.IntegerField(default=0, help_text='Used for relative sorting within the same anchor/position')),
                ('manifest', models.JSONField(default=dict)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['anchor_step', 'runtime_position', 'order_weight', 'name'],
            },
        ),
    ]
