# Generated by Django 3.2.23 on 2026-05-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='tools_config',
            field=models.JSONField(default=dict, help_text='Metadata from tools.yaml'),
        ),
    ]
