# Generated by Django 3.2.23 on 2026-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_leaklookupapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcunetixAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_url', models.CharField(max_length=500)),
                ('api_key', models.CharField(max_length=500)),
            ],
        ),
    ]
