# Generated by Django 3.2.23 on 2026-05-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_acunetixapikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censysapikey',
            old_name='api_id',
            new_name='api_key',
        ),
        migrations.RemoveField(
            model_name='censysapikey',
            name='api_secret',
        ),
    ]
