# Generated by Django 3.2.23 on 2026-05-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_hunterioapikey_linkedincredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpScanAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
