# Generated by Django 3.2.23 on 2026-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_wpscanapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_live_log_streaming', models.BooleanField(default=False)),
                ('log_retention_count', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'SOC Configuration',
                'verbose_name_plural': 'SOC Configurations',
            },
        ),
    ]
