# Generated by Django 3.2.23 on 2026-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_socconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='enable_scan_queueing',
            field=models.BooleanField(default=False),
        ),
    ]
