# Generated by Django 3.2.23 on 2026-06-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_mobilepushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepushtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
