# Generated by Django 5.2.3 on 2026-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_mobilepushtoken_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDiscoveryAPIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
            ],
        ),
    ]
