# Generated by Django 5.2.3 on 2026-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_linkedin_session_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedincredentials',
            name='username',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
