# Generated by r3ngine-plugins/keygen.py — commit this file, NEVER commit signing.key.
# Run keygen.py once, move the generated plugin_keys.py here, then rebuild plugins.
TRUSTED_PUBLIC_KEYS: list[bytes] = []
