# Generated by Django 3.2.23 on 2026-04-25 12:41
# Modified: removed django_celery_beat dependency (Phase 4G — Celery Beat removal).
# monitor_periodic_task DB column is handled via SeparateDatabaseAndState so the
# migration state doesn't reference the removed app; the column itself is dropped in 0008.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0004_opsec'),
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='last_monitored',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanEngine.enginetype'),
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_frequency',
            field=models.IntegerField(default=24, help_text='Monitoring frequency in hours'),
        ),
        # SeparateDatabaseAndState: the DB column (monitor_periodic_task_id) either
        # already exists (existing installs) or is intentionally skipped (fresh installs —
        # migration 0008 drops it with IF EXISTS so no error either way).
        # The state gets a plain IntegerField so 0008 can RemoveField it cleanly.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='domain',
                    name='monitor_periodic_task',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='monitor_scan_scope',
            field=models.CharField(choices=[('targeted', 'Targeted Scan'), ('full', 'Full Scan')], default='targeted', max_length=20),
        ),
    ]
