# Generated by Django 3.2.23 on 2026-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0003_alter_domain_monitor_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='excluded_paths',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='starting_point_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
