# Generated by Django 3.2.23 on 2026-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0004_auto_20260509_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='in_scope_ips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='secondary_domains',
            field=models.TextField(blank=True, null=True),
        ),
    ]
