# Generated by Django 3.2.23 on 2026-05-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startScan', '0029_temporal_schedule_model'),
        ('targetApp', '0005_auto_20260518_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='temporal_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_domains', to='startScan.temporalschedule'),
        ),
    ]
