# Generated by Django 5.2.3 on 2026-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0008_remove_monitor_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='target_type',
            field=models.CharField(
                choices=[
                    ('domain', 'Domain'),
                    ('host', 'Host'),
                    ('subdomain', 'Subdomain'),
                    ('url', 'URL'),
                    ('ip', 'IP Address'),
                    ('cidr', 'CIDR Range'),
                    ('email', 'Email Address'),
                    ('username', 'Username'),
                    ('phone', 'Phone Number'),
                    ('crypto_address', 'Crypto Address'),
                    ('code_path', 'Code Path / Repository'),
                ],
                db_index=True,
                default='domain',
                max_length=32,
            ),
        ),
    ]
