# Generated by Django 5.2.3 on 2026-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0009_add_target_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaininfo',
            name='whois_raw',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
