from django.urls import path

from mcp.views.audit import McpAuditListView, McpSessionEventsView
from mcp.views.keys import McpKeyListCreateView, McpKeyRegenerateView, McpKeyRevokeView
from mcp.views.dispatch import (
    McpPauseScanView,
    McpRecalculateApmeView,
    McpResumeScanView,
    McpRetryTaskView,
    McpStartEmailDiscoveryView,
    McpStartEmployeeIntelView,
    McpStartScanView,
    McpStartSubscanView,
    McpStartWorkflowView,
    McpStopEmailDiscoveryView,
    McpStopEmployeeIntelView,
    McpStopScanView,
    McpTriggerApmeView,
)
from mcp.views.read import (
    McpAttackPathsView,
    McpDashboardView,
    McpGetScanView,
    McpGetTargetView,
    McpHealthView,
    McpListEmailsView,
    McpListEmployeesView,
    McpListEndpointsView,
    McpListEnginesView,
    McpListExposuresView,
    McpListProjectsView,
    McpListScansView,
    McpListSubdomainsView,
    McpListSubscansView,
    McpListTargetsView,
    McpListVulnerabilitiesView,
    McpScanStatusView,
    McpSearchView,
)
from mcp.views.notes import McpNoteDetailView, McpNotesListCreateView
from mcp.views.sessions import (
    McpAgentDeleteView,
    McpSessionEndView,
    McpSessionHeartbeatView,
    McpSessionListCreateView,
    McpSessionRevokeView,
)
from mcp.views.settings import McpSettingsView

urlpatterns = [
    path('settings/', McpSettingsView.as_view()),
    path('keys/', McpKeyListCreateView.as_view()),
    path('keys/<int:pk>/regenerate/', McpKeyRegenerateView.as_view()),
    path('keys/<int:pk>/revoke/', McpKeyRevokeView.as_view()),
    path('sessions/', McpSessionListCreateView.as_view()),
    path('sessions/<uuid:pk>/heartbeat/', McpSessionHeartbeatView.as_view()),
    path('sessions/<uuid:pk>/end/', McpSessionEndView.as_view()),
    path('sessions/<uuid:pk>/revoke/', McpSessionRevokeView.as_view()),
    path('sessions/<uuid:pk>/events/', McpSessionEventsView.as_view()),
    path('agents/<str:agent_id>/', McpAgentDeleteView.as_view()),
    path('audit/', McpAuditListView.as_view()),
    path('projects/', McpListProjectsView.as_view()),
    path('targets/<int:pk>/', McpGetTargetView.as_view()),
    path('targets/', McpListTargetsView.as_view()),
    path('scans/<int:pk>/', McpGetScanView.as_view()),
    path('scans/', McpListScansView.as_view()),
    path('scan-status/', McpScanStatusView.as_view()),
    path('subscans/', McpListSubscansView.as_view()),
    path('subdomains/', McpListSubdomainsView.as_view()),
    path('endpoints/', McpListEndpointsView.as_view()),
    path('vulnerabilities/', McpListVulnerabilitiesView.as_view()),
    path('exposures/', McpListExposuresView.as_view()),
    path('emails/', McpListEmailsView.as_view()),
    path('employees/', McpListEmployeesView.as_view()),
    path('search/', McpSearchView.as_view()),
    path('dashboard/', McpDashboardView.as_view()),
    path('attack-paths/', McpAttackPathsView.as_view()),
    path('engines/', McpListEnginesView.as_view()),
    path('health/', McpHealthView.as_view()),
    path('notes/', McpNotesListCreateView.as_view()),
    path('notes/<int:pk>/', McpNoteDetailView.as_view()),
    path('scans/start/', McpStartScanView.as_view()),
    path('scans/pause/', McpPauseScanView.as_view()),
    path('scans/resume/', McpResumeScanView.as_view()),
    path('scans/stop/', McpStopScanView.as_view()),
    path('subscans/start/', McpStartSubscanView.as_view()),
    path('tasks/retry/', McpRetryTaskView.as_view()),
    path('email-discovery/start/', McpStartEmailDiscoveryView.as_view()),
    path('email-discovery/stop/', McpStopEmailDiscoveryView.as_view()),
    path('employee-intel/start/', McpStartEmployeeIntelView.as_view()),
    path('employee-intel/stop/', McpStopEmployeeIntelView.as_view()),
    path('apme/trigger/', McpTriggerApmeView.as_view()),
    path('apme/recalculate/', McpRecalculateApmeView.as_view()),
    path('workflows/start/', McpStartWorkflowView.as_view()),
]
