# Generated by Django 3.2.23 on 2026-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0005_vulnerabilityreportsetting_include_attack_surface_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='use_proxychains',
            field=models.BooleanField(default=False),
        ),
    ]
