# Generated by Django 5.2.3 on 2026-06-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0012_proxy_use_tor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the profile', null=True)),
                ('threads', models.IntegerField(default=10)),
                ('rate_limit', models.IntegerField(default=150)),
                ('timeout', models.IntegerField(default=10, help_text='Timeout in minutes')),
                ('delay', models.FloatField(default=0.0, help_text='Delay between requests in seconds')),
                ('retries', models.IntegerField(default=2)),
                ('profile_type', models.CharField(choices=[('builtin', 'Built-in'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
