# Generated by Django 5.2.3 on 2026-06-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0013_hardwareprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('speed', 'Speed / Throttle'), ('evasion', 'Evasion'), ('content', 'Content'), ('network', 'Network'), ('general', 'General'), ('hardware', 'Hardware')], default='general', max_length=32)),
                ('is_builtin', models.BooleanField(default=False)),
                ('rate_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('delay', models.FloatField(blank=True, null=True)),
                ('threads', models.PositiveIntegerField(blank=True, null=True)),
                ('timeout', models.PositiveIntegerField(blank=True, null=True)),
                ('retries', models.PositiveIntegerField(blank=True, null=True)),
                ('passive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('stealth', models.BooleanField(default=False)),
                ('headless', models.BooleanField(default=False)),
                ('screenshot', models.BooleanField(default=False)),
                ('hunt_secrets', models.BooleanField(default=False)),
                ('nuclei_full', models.BooleanField(default=False)),
                ('brute_dns', models.BooleanField(default=False)),
                ('brute_http', models.BooleanField(default=False)),
                ('test_ssl', models.BooleanField(default=False)),
                ('all_ports', models.BooleanField(default=False)),
                ('tor', models.BooleanField(default=False)),
                ('fragment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
