from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path(
        '',
        views.onboarding,
        name='onboarding'),
    path(
        '<slug:slug>/dashboard/',
        views.index,
        name='dashboardIndex'),
    path(
        '<slug:slug>/monitoring/',
        views.index,
        name='monitoring_dashboard'),

    path(
        '<slug:slug>/profile/',
        views.profile,
        name='profile'),
    path(
        '<slug:slug>/admin_interface/',
        views.admin_interface,
        name='admin_interface'),
    path(
        '<slug:slug>/admin_interface/update',
        views.admin_interface_update,
        name='admin_interface_update'),
    path(
        '<slug:slug>/search',
        views.search,
        name='search'),
    path(
        '404/',
        views.four_oh_four,
        name='four_oh_four'),
    path(
        '<slug:slug>/projects/',
        views.index,
        name='list_projects'),

    path(
        'delete/project/<int:id>',
        views.delete_project,
        name='delete_project'),
    path(
        '<slug:slug>/bountyhub/list/programs',
        views.list_bountyhub_programs,
        name='list_bountyhub_programs'),
    path(
        '<slug:slug>/attack_surface/<int:scan_id>/',
        views.attack_surface,
        name='attack_surface'),
    path(
        '<slug:slug>/targets/',
        views.index,
        name='targets_v3'),
    path(
        '<slug:slug>/target/<int:id>/summary',
        views.index,
        name='target_summary_v3'),
    path(
        '<slug:slug>/scans/',
        views.index,
        name='scans_v3'),
    path(
        '<slug:slug>/scan/detail/<int:id>',
        views.index,
        name='scan_detail_v3'),
    path(
        '<slug:slug>/scans/scheduled',
        views.index,
        name='scheduled_scans_v3'),
    path(
        '<slug:slug>/scans/sub',
        views.index,
        name='subscans_history_v3'),
    path(
        '<slug:slug>/vulns/',
        views.index,
        name='vulnerabilities_v3'),
    path(
        '<slug:slug>/engines/',
        views.index,
        name='engines_v3'),
    path(
        '<slug:slug>/wordlists/',
        views.index,
        name='wordlists_v3'),
    path(
        '<slug:slug>/subdomains/',
        views.index,
        name='subdomains_v3'),
    path(
        '<slug:slug>/endpoints/',
        views.index,
        name='endpoints_v3'),
    path(
        '<slug:slug>/todo/',
        views.index,
        name='todo_v3'),
    path(
        '<slug:slug>/org/',
        views.index,
        name='organizations_v3'),
    path(
        '<slug:slug>/settings/proxies',
        views.index,
        name='proxy_settings_v3'),
    path(
        '<slug:slug>/settings/opsec',
        views.index,
        name='opsec_settings_v3'),
    path(
        '<slug:slug>/settings/tool-settings',
        views.index,
        name='tool_settings_v3'),
    path(
        '<slug:slug>/settings/tool-arsenal',
        views.index,
        name='tool_arsenal_v3'),
    path(
        '<slug:slug>/settings/api-vault',
        views.index,
        name='api_vault_v3'),
    path(
        '<slug:slug>/settings/llm-toolkit',
        views.index,
        name='llm_toolkit_v3'),
    path(
        '<slug:slug>/bounty',
        views.index,
        name='bounty_v3'),
    path(
        '<slug:slug>/api/graph/scan/<int:scan_id>/data/',
        views.get_graph_data,
        name='get_graph_data'),
]
